FROM openjdk:8

WORKDIR /app

# Instalação de Dependências
RUN apt-get update && apt-get install -y wget unzip gettext && rm -rf /var/lib/apt/lists/*

# Criação de pasta segura para os JARs fora do volume
RUN mkdir -p /opt/embulk

# Carregamento de dependências embulk.jar e jruby-complete.jar para /opt/embulk
RUN wget https://github.com/embulk/embulk/releases/download/v0.9.25/embulk-0.9.25.jar -O /opt/embulk/embulk.jar && \
    wget https://repo1.maven.org/maven2/org/jruby/jruby-complete/9.1.15.0/jruby-complete-9.1.15.0.jar -O /opt/embulk/jruby-complete.jar && \
    chmod +x /opt/embulk/embulk.jar

# Baixo o yq (utilitário para manipulação de YAML via linha de comando)
RUN wget https://github.com/mikefarah/yq/releases/download/v4.40.5/yq_linux_amd64 -O /usr/bin/yq && \
    chmod +x /usr/bin/yq

# Copio todos os arquivos do projeto para dentro da imagem
COPY . .

# Deixo os scripts shell prontos para execução (evita erro de permissão)
RUN chmod +x entrypoint.sh scripts/*.sh

# Defino o entrypoint padrão da aplicação
ENTRYPOINT ["sh", "./entrypoint.sh"]


