# Dockerfile (Meltano)
FROM python:3.10-slim

WORKDIR /app

COPY . .

RUN apt-get update && \
    apt-get install -y build-essential gcc && \
    pip install --upgrade pip && \
    pip install meltano && \
    pip install -e plugins/custom/tap-aw-api && \
    apt-get remove -y build-essential gcc && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/* 

# Garante que o script de entrada tenha permissão de execução
RUN chmod +x entrypoint.sh

ENTRYPOINT ["sh", "entrypoint.sh"]